---
- hosts: all #run vs all hosts of your inventory
  gather_facts: no
  become: false #do not become root
  pre_tasks:
  - name: Clone Git Repository #clone script code from gitlab
    tags: git
    git:
      repo: https://gitlab.com/iexos/caldav2telegram.git
      dest: ~/caldav2telegram
  - name: Create virtual environment #to make sure pip is latest version
    tags: venv
    pip:
      name:
        - pyYAML
        - pytz
        - icalendar
        - caldav
      state: latest
      virtualenv: ~/caldav2telegram
  tasks:
  - name: Install python-telegram-bot #only required when posting to telegram
    tags: telegram
    pip:
      name: python-telegram-bot
      version: '13.0'
      virtualenv: ~/caldav2telegram
  - name: Copy Config File to Server #this requires the example config to be stored in ./files/default_config.yml (relative to your playbook)
    tags: config
    copy:
      src: ~/config.example.yml
      dest: ~/caldav2telegram/src/config.yml
      owner: root
      group: root
      mode: 0000
